title: Open&nbsp;Samenwerking<br>en Innovatie<br>in Public&nbsp;Tech
quote: inspiratie ∞ innovatie
description: >
  public tech ondernemer met een achtergrond in natural computing en Software design.
  Onstopbare brainstormer die kansen ziet en mensen, ideeën, en initiatieven verbindt.