title: Open&nbsp;Samenwerking<br>en Innovatie<br>in Public&nbsp;Tech
description: >
  #publictech ondernemer met een achtergrond in #naturalcomputing en #softwaredesign.
  Onstopbare brainstormer die kansen ziet en mensen, ideeën, en initiatieven verbindt.